spring:
  application:
    name: rh-reference-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/rh
    username: rh
    password: rh
  data:
    web:
      pageable:
        max-page-size: 100
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/master.xml
    drop-first: true
  jackson:
    default-property-inclusion: non-null

app:
  security:
    jwt:
      secret: demo-jwt-secret-change-me-1234567890
      issuer: crud-reference
      ttl: PT1H
    cors:
      allowed-origins:
        - http://localhost:9000
