CREATE TABLE departement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    nom VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT uk_departement_nom UNIQUE (nom),
    CONSTRAINT ck_departement_nom_non_vide CHECK (btrim(nom) <> '')
);

CREATE TABLE sexe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    libelle VARCHAR(250) NOT NULL,
    CONSTRAINT uk_sexe_libelle UNIQUE (libelle),
    CONSTRAINT ck_sexe_libelle_non_vide CHECK (btrim(libelle) <> '')
);

CREATE TABLE situation_familiale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    libelle VARCHAR(250) NOT NULL,
    CONSTRAINT uk_situation_familiale_libelle UNIQUE (libelle),
    CONSTRAINT ck_situation_familiale_libelle_non_vide CHECK (btrim(libelle) <> '')
);

CREATE TABLE employe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    matricule VARCHAR(250) NOT NULL,
    nom VARCHAR(250) NOT NULL,
    prenom VARCHAR(250) NOT NULL,
    date_naissance DATE NOT NULL,
    sexe_id BIGINT,
    situation_familiale_id BIGINT,
    date_entree DATE,
    email VARCHAR(250),
    telephone VARCHAR(250),
    ville VARCHAR(250),
    adresse VARCHAR(250),
    fonction VARCHAR(250),
    description TEXT,
    departement_id BIGINT,
    CONSTRAINT uk_employe_matricule UNIQUE (matricule),
    CONSTRAINT ck_employe_matricule_non_vide CHECK (btrim(matricule) <> ''),
    CONSTRAINT ck_employe_nom_non_vide CHECK (btrim(nom) <> ''),
    CONSTRAINT ck_employe_prenom_non_vide CHECK (btrim(prenom) <> ''),
    CONSTRAINT fk_employe_sexe
        FOREIGN KEY (sexe_id) REFERENCES sexe (id) ON DELETE RESTRICT,
    CONSTRAINT fk_employe_situation_familiale
        FOREIGN KEY (situation_familiale_id) REFERENCES situation_familiale (id) ON DELETE RESTRICT,
    CONSTRAINT fk_employe_departement
        FOREIGN KEY (departement_id) REFERENCES departement (id) ON DELETE RESTRICT
);

CREATE INDEX ix_employe_sexe ON employe (sexe_id);
CREATE INDEX ix_employe_situation_familiale ON employe (situation_familiale_id);
CREATE INDEX ix_employe_departement ON employe (departement_id);
CREATE INDEX ix_employe_date_naissance ON employe (date_naissance);
CREATE INDEX ix_employe_date_entree ON employe (date_entree);

CREATE TABLE conge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    motif VARCHAR(2000),
    employe_id BIGINT NOT NULL,
    CONSTRAINT ck_conge_ordre_dates CHECK (date_fin >= date_debut),
    CONSTRAINT fk_conge_employe
        FOREIGN KEY (employe_id) REFERENCES employe (id) ON DELETE RESTRICT
);

CREATE INDEX ix_conge_employe_dates ON conge (employe_id, date_debut, id);

CREATE TABLE app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    code VARCHAR(50) NOT NULL,
    libelle VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT uk_app_role_code UNIQUE (code),
    CONSTRAINT ck_app_role_code_format CHECK (code ~ '^[A-Z][A-Z0-9_]{1,49}$'),
    CONSTRAINT ck_app_role_libelle_non_vide CHECK (btrim(libelle) <> ''),
    CONSTRAINT ck_app_role_libelle_canonique CHECK (libelle = btrim(libelle))
);

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    username VARCHAR(100) NOT NULL,
    display_name VARCHAR(150) NOT NULL,
    email VARCHAR(254),
    active BOOLEAN NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT uk_account_username UNIQUE (username),
    CONSTRAINT uk_account_email UNIQUE (email),
    CONSTRAINT ck_account_username_format CHECK (username ~ '^[a-z0-9._-]{3,100}$'),
    CONSTRAINT ck_account_display_name_non_vide CHECK (btrim(display_name) <> ''),
    CONSTRAINT ck_account_display_name_canonique CHECK (display_name = btrim(display_name)),
    CONSTRAINT ck_account_email_canonique CHECK (
        email IS NULL OR (email = lower(btrim(email)) AND btrim(email) <> '')
    ),
    CONSTRAINT fk_account_role
        FOREIGN KEY (role_id) REFERENCES app_role (id) ON DELETE RESTRICT
);

CREATE INDEX ix_account_role ON account (role_id);
CREATE INDEX ix_account_active ON account (active);

CREATE TABLE account_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    account_id BIGINT NOT NULL,
    password_hash VARCHAR(500) NOT NULL,
    token_version BIGINT NOT NULL DEFAULT 0,
    password_changed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_account_credential_account UNIQUE (account_id),
    CONSTRAINT ck_account_credential_hash_non_vide CHECK (btrim(password_hash) <> ''),
    CONSTRAINT ck_account_credential_token_version CHECK (token_version >= 0),
    CONSTRAINT fk_account_credential_account
        FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE
);
