CREATE TABLE type_conge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    libelle VARCHAR(250) NOT NULL,
    CONSTRAINT uk_type_conge_libelle UNIQUE (libelle),
    CONSTRAINT ck_type_conge_libelle_non_vide CHECK (btrim(libelle) <> '')
);

ALTER TABLE conge RENAME COLUMN date_debut TO date_debut_conge;
ALTER TABLE conge RENAME COLUMN date_fin TO date_fin_conge;
ALTER TABLE conge RENAME COLUMN motif TO commentaire;

ALTER TABLE conge ALTER COLUMN date_debut_conge DROP NOT NULL;
ALTER TABLE conge ALTER COLUMN date_fin_conge DROP NOT NULL;
ALTER TABLE conge ALTER COLUMN commentaire TYPE TEXT;

ALTER TABLE conge ADD COLUMN code VARCHAR(250);
UPDATE conge SET code = 'CONGE-' || id;
ALTER TABLE conge ALTER COLUMN code SET NOT NULL;
ALTER TABLE conge ADD COLUMN type_conge_id BIGINT;

ALTER TABLE conge DROP CONSTRAINT ck_conge_ordre_dates;
ALTER TABLE conge ADD CONSTRAINT uk_conge_code UNIQUE (code);
ALTER TABLE conge ADD CONSTRAINT ck_conge_code_non_vide CHECK (btrim(code) <> '');
ALTER TABLE conge ADD CONSTRAINT fk_conge_type_conge
    FOREIGN KEY (type_conge_id) REFERENCES type_conge (id) ON DELETE RESTRICT;

DROP INDEX ix_conge_employe_dates;
CREATE INDEX ix_conge_employe_code ON conge (employe_id, code);
CREATE INDEX ix_conge_type_conge ON conge (type_conge_id);
